const CURRENT_WEATHER_ATTEMPT = "CURRENT_WEATHER_ATTEMPT";
const CURRENT_WEATHER_SUCCESS = "CURRENT_WEATHER_SUCCESS";
const CURRENT_WEATHER_FAILURE = "CURRENT_WEATHER_FAILURE";

export default {
  CURRENT_WEATHER_ATTEMPT,
  CURRENT_WEATHER_SUCCESS,
  CURRENT_WEATHER_FAILURE,
};
