const FORECASTS_ATTEMPT = "FORECASTS_ATTEMPT";
const FORECASTS_SUCCESS = "FORECASTS_SUCCESS";
const FORECASTS_FAILURE = "FORECASTS_FAILURE";

export default {
  FORECASTS_ATTEMPT,
  FORECASTS_SUCCESS,
  FORECASTS_FAILURE,
};
